// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "priority", Type: field.TypeInt32, Nullable: true},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
	}
	// DescriptionsColumns holds the columns for the "descriptions" table.
	DescriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "application_descriptions", Type: field.TypeInt, Nullable: true},
		{Name: "experience_descriptions", Type: field.TypeInt, Nullable: true},
	}
	// DescriptionsTable holds the schema information for the "descriptions" table.
	DescriptionsTable = &schema.Table{
		Name:       "descriptions",
		Columns:    DescriptionsColumns,
		PrimaryKey: []*schema.Column{DescriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "descriptions_applications_descriptions",
				Columns:    []*schema.Column{DescriptionsColumns[3]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "descriptions_experiences_descriptions",
				Columns:    []*schema.Column{DescriptionsColumns[4]},
				RefColumns: []*schema.Column{ExperiencesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EducationsColumns holds the columns for the "educations" table.
	EducationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "school", Type: field.TypeString},
		{Name: "time", Type: field.TypeString, Nullable: true},
		{Name: "certificate", Type: field.TypeString, Nullable: true},
		{Name: "degree", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "priority", Type: field.TypeInt32, Nullable: true},
	}
	// EducationsTable holds the schema information for the "educations" table.
	EducationsTable = &schema.Table{
		Name:       "educations",
		Columns:    EducationsColumns,
		PrimaryKey: []*schema.Column{EducationsColumns[0]},
	}
	// ExperiencesColumns holds the columns for the "experiences" table.
	ExperiencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "employer", Type: field.TypeString},
		{Name: "position", Type: field.TypeString},
		{Name: "time", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// ExperiencesTable holds the schema information for the "experiences" table.
	ExperiencesTable = &schema.Table{
		Name:       "experiences",
		Columns:    ExperiencesColumns,
		PrimaryKey: []*schema.Column{ExperiencesColumns[0]},
	}
	// InvitesColumns holds the columns for the "invites" table.
	InvitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "registered", Type: field.TypeBool, Default: false},
		{Name: "user_invite", Type: field.TypeInt, Nullable: true},
	}
	// InvitesTable holds the schema information for the "invites" table.
	InvitesTable = &schema.Table{
		Name:       "invites",
		Columns:    InvitesColumns,
		PrimaryKey: []*schema.Column{InvitesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invites_users_invite",
				Columns:    []*schema.Column{InvitesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TechStacksColumns holds the columns for the "tech_stacks" table.
	TechStacksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "stack", Type: field.TypeString},
	}
	// TechStacksTable holds the schema information for the "tech_stacks" table.
	TechStacksTable = &schema.Table{
		Name:       "tech_stacks",
		Columns:    TechStacksColumns,
		PrimaryKey: []*schema.Column{TechStacksColumns[0]},
	}
	// TechnologiesColumns holds the columns for the "technologies" table.
	TechnologiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "priority", Type: field.TypeInt32},
		{Name: "application_technologies", Type: field.TypeInt, Nullable: true},
		{Name: "tech_stack_technology", Type: field.TypeInt, Nullable: true},
	}
	// TechnologiesTable holds the schema information for the "technologies" table.
	TechnologiesTable = &schema.Table{
		Name:       "technologies",
		Columns:    TechnologiesColumns,
		PrimaryKey: []*schema.Column{TechnologiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "technologies_applications_technologies",
				Columns:    []*schema.Column{TechnologiesColumns[4]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "technologies_tech_stacks_technology",
				Columns:    []*schema.Column{TechnologiesColumns[5]},
				RefColumns: []*schema.Column{TechStacksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TestsColumns holds the columns for the "tests" table.
	TestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// TestsTable holds the schema information for the "tests" table.
	TestsTable = &schema.Table{
		Name:       "tests",
		Columns:    TestsColumns,
		PrimaryKey: []*schema.Column{TestsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "hash", Type: field.TypeString},
		{Name: "salt", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApplicationsTable,
		DescriptionsTable,
		EducationsTable,
		ExperiencesTable,
		InvitesTable,
		TechStacksTable,
		TechnologiesTable,
		TestsTable,
		UsersTable,
	}
)

func init() {
	DescriptionsTable.ForeignKeys[0].RefTable = ApplicationsTable
	DescriptionsTable.ForeignKeys[1].RefTable = ExperiencesTable
	InvitesTable.ForeignKeys[0].RefTable = UsersTable
	TechnologiesTable.ForeignKeys[0].RefTable = ApplicationsTable
	TechnologiesTable.ForeignKeys[1].RefTable = TechStacksTable
}
