// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"kylejohnson-xyz/ent/description"
	"kylejohnson-xyz/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DescriptionDelete is the builder for deleting a Description entity.
type DescriptionDelete struct {
	config
	hooks    []Hook
	mutation *DescriptionMutation
}

// Where appends a list predicates to the DescriptionDelete builder.
func (dd *DescriptionDelete) Where(ps ...predicate.Description) *DescriptionDelete {
	dd.mutation.Where(ps...)
	return dd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dd *DescriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, DescriptionMutation](ctx, dd.sqlExec, dd.mutation, dd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dd *DescriptionDelete) ExecX(ctx context.Context) int {
	n, err := dd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dd *DescriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(description.Table, sqlgraph.NewFieldSpec(description.FieldID, field.TypeInt))
	if ps := dd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dd.mutation.done = true
	return affected, err
}

// DescriptionDeleteOne is the builder for deleting a single Description entity.
type DescriptionDeleteOne struct {
	dd *DescriptionDelete
}

// Where appends a list predicates to the DescriptionDelete builder.
func (ddo *DescriptionDeleteOne) Where(ps ...predicate.Description) *DescriptionDeleteOne {
	ddo.dd.mutation.Where(ps...)
	return ddo
}

// Exec executes the deletion query.
func (ddo *DescriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := ddo.dd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{description.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddo *DescriptionDeleteOne) ExecX(ctx context.Context) {
	if err := ddo.Exec(ctx); err != nil {
		panic(err)
	}
}
