// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kylejohnson-xyz/ent/application"
	"kylejohnson-xyz/ent/description"
	"kylejohnson-xyz/ent/education"
	"kylejohnson-xyz/ent/experience"
	"kylejohnson-xyz/ent/invite"
	"kylejohnson-xyz/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	applicationFields := schema.Application{}.Fields()
	_ = applicationFields
	// applicationDescActive is the schema descriptor for active field.
	applicationDescActive := applicationFields[2].Descriptor()
	// application.DefaultActive holds the default value on creation for the active field.
	application.DefaultActive = applicationDescActive.Default.(bool)
	descriptionFields := schema.Description{}.Fields()
	_ = descriptionFields
	// descriptionDescActive is the schema descriptor for active field.
	descriptionDescActive := descriptionFields[1].Descriptor()
	// description.DefaultActive holds the default value on creation for the active field.
	description.DefaultActive = descriptionDescActive.Default.(bool)
	educationFields := schema.Education{}.Fields()
	_ = educationFields
	// educationDescActive is the schema descriptor for active field.
	educationDescActive := educationFields[4].Descriptor()
	// education.DefaultActive holds the default value on creation for the active field.
	education.DefaultActive = educationDescActive.Default.(bool)
	experienceFields := schema.Experience{}.Fields()
	_ = experienceFields
	// experienceDescActive is the schema descriptor for active field.
	experienceDescActive := experienceFields[3].Descriptor()
	// experience.DefaultActive holds the default value on creation for the active field.
	experience.DefaultActive = experienceDescActive.Default.(bool)
	inviteFields := schema.Invite{}.Fields()
	_ = inviteFields
	// inviteDescRegistered is the schema descriptor for registered field.
	inviteDescRegistered := inviteFields[2].Descriptor()
	// invite.DefaultRegistered holds the default value on creation for the registered field.
	invite.DefaultRegistered = inviteDescRegistered.Default.(bool)
}
