// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kylejohnson-xyz/ent/technology"
	"kylejohnson-xyz/ent/techstack"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TechStackCreate is the builder for creating a TechStack entity.
type TechStackCreate struct {
	config
	mutation *TechStackMutation
	hooks    []Hook
}

// SetStack sets the "stack" field.
func (tsc *TechStackCreate) SetStack(s string) *TechStackCreate {
	tsc.mutation.SetStack(s)
	return tsc
}

// SetID sets the "id" field.
func (tsc *TechStackCreate) SetID(u uuid.UUID) *TechStackCreate {
	tsc.mutation.SetID(u)
	return tsc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tsc *TechStackCreate) SetNillableID(u *uuid.UUID) *TechStackCreate {
	if u != nil {
		tsc.SetID(*u)
	}
	return tsc
}

// AddTechnologyIDs adds the "technology" edge to the Technology entity by IDs.
func (tsc *TechStackCreate) AddTechnologyIDs(ids ...uuid.UUID) *TechStackCreate {
	tsc.mutation.AddTechnologyIDs(ids...)
	return tsc
}

// AddTechnology adds the "technology" edges to the Technology entity.
func (tsc *TechStackCreate) AddTechnology(t ...*Technology) *TechStackCreate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tsc.AddTechnologyIDs(ids...)
}

// Mutation returns the TechStackMutation object of the builder.
func (tsc *TechStackCreate) Mutation() *TechStackMutation {
	return tsc.mutation
}

// Save creates the TechStack in the database.
func (tsc *TechStackCreate) Save(ctx context.Context) (*TechStack, error) {
	tsc.defaults()
	return withHooks[*TechStack, TechStackMutation](ctx, tsc.sqlSave, tsc.mutation, tsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tsc *TechStackCreate) SaveX(ctx context.Context) *TechStack {
	v, err := tsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tsc *TechStackCreate) Exec(ctx context.Context) error {
	_, err := tsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsc *TechStackCreate) ExecX(ctx context.Context) {
	if err := tsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tsc *TechStackCreate) defaults() {
	if _, ok := tsc.mutation.ID(); !ok {
		v := techstack.DefaultID()
		tsc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsc *TechStackCreate) check() error {
	if _, ok := tsc.mutation.Stack(); !ok {
		return &ValidationError{Name: "stack", err: errors.New(`ent: missing required field "TechStack.stack"`)}
	}
	return nil
}

func (tsc *TechStackCreate) sqlSave(ctx context.Context) (*TechStack, error) {
	if err := tsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tsc.mutation.id = &_node.ID
	tsc.mutation.done = true
	return _node, nil
}

func (tsc *TechStackCreate) createSpec() (*TechStack, *sqlgraph.CreateSpec) {
	var (
		_node = &TechStack{config: tsc.config}
		_spec = sqlgraph.NewCreateSpec(techstack.Table, sqlgraph.NewFieldSpec(techstack.FieldID, field.TypeUUID))
	)
	if id, ok := tsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tsc.mutation.Stack(); ok {
		_spec.SetField(techstack.FieldStack, field.TypeString, value)
		_node.Stack = value
	}
	if nodes := tsc.mutation.TechnologyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   techstack.TechnologyTable,
			Columns: []string{techstack.TechnologyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TechStackCreateBulk is the builder for creating many TechStack entities in bulk.
type TechStackCreateBulk struct {
	config
	builders []*TechStackCreate
}

// Save creates the TechStack entities in the database.
func (tscb *TechStackCreateBulk) Save(ctx context.Context) ([]*TechStack, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tscb.builders))
	nodes := make([]*TechStack, len(tscb.builders))
	mutators := make([]Mutator, len(tscb.builders))
	for i := range tscb.builders {
		func(i int, root context.Context) {
			builder := tscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TechStackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tscb *TechStackCreateBulk) SaveX(ctx context.Context) []*TechStack {
	v, err := tscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tscb *TechStackCreateBulk) Exec(ctx context.Context) error {
	_, err := tscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tscb *TechStackCreateBulk) ExecX(ctx context.Context) {
	if err := tscb.Exec(ctx); err != nil {
		panic(err)
	}
}
