// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"kylejohnson-xyz/ent/predicate"
	"kylejohnson-xyz/ent/technology"
	"kylejohnson-xyz/ent/techstack"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TechStackQuery is the builder for querying TechStack entities.
type TechStackQuery struct {
	config
	ctx            *QueryContext
	order          []techstack.OrderOption
	inters         []Interceptor
	predicates     []predicate.TechStack
	withTechnology *TechnologyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TechStackQuery builder.
func (tsq *TechStackQuery) Where(ps ...predicate.TechStack) *TechStackQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit the number of records to be returned by this query.
func (tsq *TechStackQuery) Limit(limit int) *TechStackQuery {
	tsq.ctx.Limit = &limit
	return tsq
}

// Offset to start from.
func (tsq *TechStackQuery) Offset(offset int) *TechStackQuery {
	tsq.ctx.Offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TechStackQuery) Unique(unique bool) *TechStackQuery {
	tsq.ctx.Unique = &unique
	return tsq
}

// Order specifies how the records should be ordered.
func (tsq *TechStackQuery) Order(o ...techstack.OrderOption) *TechStackQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// QueryTechnology chains the current query on the "technology" edge.
func (tsq *TechStackQuery) QueryTechnology() *TechnologyQuery {
	query := (&TechnologyClient{config: tsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(techstack.Table, techstack.FieldID, selector),
			sqlgraph.To(technology.Table, technology.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, techstack.TechnologyTable, techstack.TechnologyColumn),
		)
		fromU = sqlgraph.SetNeighbors(tsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TechStack entity from the query.
// Returns a *NotFoundError when no TechStack was found.
func (tsq *TechStackQuery) First(ctx context.Context) (*TechStack, error) {
	nodes, err := tsq.Limit(1).All(setContextOp(ctx, tsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{techstack.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TechStackQuery) FirstX(ctx context.Context) *TechStack {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TechStack ID from the query.
// Returns a *NotFoundError when no TechStack ID was found.
func (tsq *TechStackQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(1).IDs(setContextOp(ctx, tsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{techstack.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TechStackQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TechStack entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TechStack entity is found.
// Returns a *NotFoundError when no TechStack entities are found.
func (tsq *TechStackQuery) Only(ctx context.Context) (*TechStack, error) {
	nodes, err := tsq.Limit(2).All(setContextOp(ctx, tsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{techstack.Label}
	default:
		return nil, &NotSingularError{techstack.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TechStackQuery) OnlyX(ctx context.Context) *TechStack {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TechStack ID in the query.
// Returns a *NotSingularError when more than one TechStack ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TechStackQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(2).IDs(setContextOp(ctx, tsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{techstack.Label}
	default:
		err = &NotSingularError{techstack.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TechStackQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TechStacks.
func (tsq *TechStackQuery) All(ctx context.Context) ([]*TechStack, error) {
	ctx = setContextOp(ctx, tsq.ctx, "All")
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TechStack, *TechStackQuery]()
	return withInterceptors[[]*TechStack](ctx, tsq, qr, tsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TechStackQuery) AllX(ctx context.Context) []*TechStack {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TechStack IDs.
func (tsq *TechStackQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tsq.ctx.Unique == nil && tsq.path != nil {
		tsq.Unique(true)
	}
	ctx = setContextOp(ctx, tsq.ctx, "IDs")
	if err = tsq.Select(techstack.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TechStackQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TechStackQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Count")
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tsq, querierCount[*TechStackQuery](), tsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TechStackQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TechStackQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Exist")
	switch _, err := tsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TechStackQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TechStackQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TechStackQuery) Clone() *TechStackQuery {
	if tsq == nil {
		return nil
	}
	return &TechStackQuery{
		config:         tsq.config,
		ctx:            tsq.ctx.Clone(),
		order:          append([]techstack.OrderOption{}, tsq.order...),
		inters:         append([]Interceptor{}, tsq.inters...),
		predicates:     append([]predicate.TechStack{}, tsq.predicates...),
		withTechnology: tsq.withTechnology.Clone(),
		// clone intermediate query.
		sql:  tsq.sql.Clone(),
		path: tsq.path,
	}
}

// WithTechnology tells the query-builder to eager-load the nodes that are connected to
// the "technology" edge. The optional arguments are used to configure the query builder of the edge.
func (tsq *TechStackQuery) WithTechnology(opts ...func(*TechnologyQuery)) *TechStackQuery {
	query := (&TechnologyClient{config: tsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tsq.withTechnology = query
	return tsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Stack string `json:"stack,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TechStack.Query().
//		GroupBy(techstack.FieldStack).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tsq *TechStackQuery) GroupBy(field string, fields ...string) *TechStackGroupBy {
	tsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TechStackGroupBy{build: tsq}
	grbuild.flds = &tsq.ctx.Fields
	grbuild.label = techstack.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Stack string `json:"stack,omitempty"`
//	}
//
//	client.TechStack.Query().
//		Select(techstack.FieldStack).
//		Scan(ctx, &v)
func (tsq *TechStackQuery) Select(fields ...string) *TechStackSelect {
	tsq.ctx.Fields = append(tsq.ctx.Fields, fields...)
	sbuild := &TechStackSelect{TechStackQuery: tsq}
	sbuild.label = techstack.Label
	sbuild.flds, sbuild.scan = &tsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TechStackSelect configured with the given aggregations.
func (tsq *TechStackQuery) Aggregate(fns ...AggregateFunc) *TechStackSelect {
	return tsq.Select().Aggregate(fns...)
}

func (tsq *TechStackQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tsq); err != nil {
				return err
			}
		}
	}
	for _, f := range tsq.ctx.Fields {
		if !techstack.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TechStackQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TechStack, error) {
	var (
		nodes       = []*TechStack{}
		_spec       = tsq.querySpec()
		loadedTypes = [1]bool{
			tsq.withTechnology != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TechStack).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TechStack{config: tsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tsq.withTechnology; query != nil {
		if err := tsq.loadTechnology(ctx, query, nodes,
			func(n *TechStack) { n.Edges.Technology = []*Technology{} },
			func(n *TechStack, e *Technology) { n.Edges.Technology = append(n.Edges.Technology, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tsq *TechStackQuery) loadTechnology(ctx context.Context, query *TechnologyQuery, nodes []*TechStack, init func(*TechStack), assign func(*TechStack, *Technology)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*TechStack)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Technology(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(techstack.TechnologyColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tech_stack_technology
		if fk == nil {
			return fmt.Errorf(`foreign-key "tech_stack_technology" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tech_stack_technology" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tsq *TechStackQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	_spec.Node.Columns = tsq.ctx.Fields
	if len(tsq.ctx.Fields) > 0 {
		_spec.Unique = tsq.ctx.Unique != nil && *tsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TechStackQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(techstack.Table, techstack.Columns, sqlgraph.NewFieldSpec(techstack.FieldID, field.TypeUUID))
	_spec.From = tsq.sql
	if unique := tsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tsq.path != nil {
		_spec.Unique = true
	}
	if fields := tsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, techstack.FieldID)
		for i := range fields {
			if fields[i] != techstack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TechStackQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(techstack.Table)
	columns := tsq.ctx.Fields
	if len(columns) == 0 {
		columns = techstack.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.ctx.Unique != nil && *tsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TechStackGroupBy is the group-by builder for TechStack entities.
type TechStackGroupBy struct {
	selector
	build *TechStackQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TechStackGroupBy) Aggregate(fns ...AggregateFunc) *TechStackGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the selector query and scans the result into the given value.
func (tsgb *TechStackGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tsgb.build.ctx, "GroupBy")
	if err := tsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TechStackQuery, *TechStackGroupBy](ctx, tsgb.build, tsgb, tsgb.build.inters, v)
}

func (tsgb *TechStackGroupBy) sqlScan(ctx context.Context, root *TechStackQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tsgb.flds)+len(tsgb.fns))
		for _, f := range *tsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TechStackSelect is the builder for selecting fields of TechStack entities.
type TechStackSelect struct {
	*TechStackQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tss *TechStackSelect) Aggregate(fns ...AggregateFunc) *TechStackSelect {
	tss.fns = append(tss.fns, fns...)
	return tss
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TechStackSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tss.ctx, "Select")
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TechStackQuery, *TechStackSelect](ctx, tss.TechStackQuery, tss, tss.inters, v)
}

func (tss *TechStackSelect) sqlScan(ctx context.Context, root *TechStackQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tss.fns))
	for _, fn := range tss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
