// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// Description is the predicate function for description builders.
type Description func(*sql.Selector)

// Education is the predicate function for education builders.
type Education func(*sql.Selector)

// Experience is the predicate function for experience builders.
type Experience func(*sql.Selector)

// Invite is the predicate function for invite builders.
type Invite func(*sql.Selector)

// TechStack is the predicate function for techstack builders.
type TechStack func(*sql.Selector)

// Technology is the predicate function for technology builders.
type Technology func(*sql.Selector)

// Test is the predicate function for test builders.
type Test func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
